unitaryfoundation/ucc

README.md, docs/source/api.rst, docs/source/conf.py, docs/source/index.rst, requirements.txt
=> 167 add readmemd to documentation

.readthedocs.yml
Fixes #179 . 
Adds our Sphinx path explicitly to `.readthedocs.yaml` . 
Otherwise RTD will no longer build UCC docs. 😿
=> Add explicit Sphinx config in `.readthedocs.yaml` file

README.md, docs/source/user_guide.rst
Originally opened to update readme with python version requirement and fix rendering of that requirement in the user guide.
Also fixes import in #204 - import from `benchmarking` not `ucc.benchmarking`
=> Minor docs updates

benchmarks/run_ucc_benchmarks.ipynb
Trying to reproduce error when UCC benchmarks didn't run as expected: https://github.com/unitaryfund/ucc/actions/runs/13125410128 (results)
https://github.com/unitaryfund/ucc/actions/runs/13125252118 (benchmark run and re-run)
This PR just changes "Unitary Fund: to "Unitary Foundation" in the explanatory text of `run_benchmarks.ipynb` .
=> Wording change to force run benchmarks

.github/workflows/ucc-benchmarks.yml, .gitignore, Dockerfile
When initially refactoring to use poetry, the Dockerfile used in the benchmark task stored the virtual env directory within the package working directory.
However, the github actions benchmark script maps the runner's working copy of the ucc directory to the dockerfile run of the benchmark script. This shadows the /ucc/.venv directory.
This fix switches to store the virtual environment directory outside the package working directory to avoid this shadowing.
Fixes #212
=> Fix benchmark script to work with poetry

.readthedocs.yml
Fixes #218.
Was a 1 letter typo, as I had created the `doc` dependency group in the `pyproject.toml` as part of the shift to poetry, but had changed the RTD conf to install the non-existent `doc*s*` dependency group.
=> Fix read-the-docs build

README.md
When starting to work on #202 I noticed this minor type on the function that describes supported formats.
=> Fix typo in readme for supported formats

benchmarks/scripts/plot_latest_expval_benchmarks.py
In order to run this script as part of the github actions pipeline, it should be runnable from any location.
=> Fix relative path bug in expval benchmarking script

benchmarks/scripts/common.py, benchmarks/tests/test_common.py
`cirq`'s optimize_for_target_gateset function requires providing a class that compiles to a desired target gateset. None of the cirq provided target gatesets use the set of gates we consider for benchmarking, so this change adds an appropriate one with our desired basis.
Fixes #201 .
=> Add target gate set for cirq benchmarking

README.md, docs/source/benchmarking.rst, docs/source/dev.rst, docs/source/index.rst
Updates the README to add more context on UCC's goals and place in the ecosystem.
Adds a benchmarking section to the docs to give more details on the benchmark suite design and how users can contribute or suggest improvements.
Attempts to address both #242 and #202.
=> Update documentation to expand on design goals:

poetry.lock
#125 will automate this, but for now, upgrading to the latest version of pyqasm and qbraid to benefit from improvements in parsing speed during benchmark runs.
Fixes #233
=> Upgrade dependencies

benchmarks/scripts/expval_benchmark.py
Per [comments](https://github.com/unitaryfund/ucc/pull/223#discussion_r1960319404) in #223, we need a stronger justification for varying error rates. We may wish to do so later to solve #222 but it needs more investigation.
This PR is to use the global error rates consistently for noisy simulation in `expval_benchmark.py`.
=> Change QV error rates back to global variables

.github/workflows/test.yml
I want to test the functionality of a change before checking the formatting. In this way you get a failure like on an unused import before the code itself runs: https://github.com/unitaryfund/ucc/actions/runs/13554895918/job/37886926715
=> Run pytest before ruff linter checks

.github/workflows/ucc-benchmarks.yml, Dockerfile, benchmarks/scripts/expval_benchmark.py, benchmarks/scripts/run_benchmarks.sh
These changes will
1. Reduce the parallelism in the benchmarking runs to minimize contention that might otherwise impact the results. This includes restricting Qiskit-AER simulations to a maximum of 1 parallel thread and run expected value benchmarks separate in parallel separate from timing benchmarks in parallel. ~~and forcing just 1 parallel job in the benchmark script itself~~.
2. Use the locked version of dependencies in the benchmarking runs to avoid an uncontrolled change in a dependent library or transitive dependency.
3. Ensure only one instance of the benchmark github workflow runs at a time by specifying a concurrency group.
This partially addresses #251
=> Improve reproducibility and consistency of benchmarking workflow

README.md
Since we are now using only a combination of out of the box Qiskit passes.
=> remove README reference to customized passes

ucc/compile.py, ucc/tests/test_compile.py, ucc/transpilers/ucc_defaults.py
Fixes #288 by using the specified `target_device`, not just the coupling map, when provided to `compile` or `UCCDefault1`.
=> Use target_device if specified, not just connectivity, when compiling

benchmarks/scripts/common.py, benchmarks/scripts/plot_avg_benchmarks_over_time.py, benchmarks/scripts/plot_expval_benchmarks_over_time.py
Fixes #200.
Change plot resolution to per compiler release in plot over time scripts, so the plots will look like the following:
Note: I pasted (instead of pushed) these plots because they'd have to be removed before merge anyway.
=> Change plot resolution to per release in plot over time scripts

docs/source/user_guide.rst, ucc/compile.py, ucc/tests/test_compile.py
Following the discussion in #292, adds a `custom_passes` argument to `compile`.
I also removed some now stale parts of the docs, but we should consider a separate issue/PR to add more details on the choice of passes in `UCCDefault`.
Resolves #292
=> Support custom passes in compile

.github/workflows/python-publish.yml
Add an automated workflow file for publishing to PyPI, which should run automatically upon a release. 
It includes a test upload to TestPyPI and then requires manual approval from @jordandsullivan , @Misty-W , or @bachase to publish to real PyPI. 
Need to merge into main to be able to test the manual dispatch function.
=> Create first draft of python-publish.yml

.github/workflows/python-publish.yml
This will allow us to manually trigger a deployment to PyPI, in addition to automatically triggering upon a release. The relevant code change is [here](https://github.com/unitaryfund/ucc/pull/311/files#diff-87c8be2ac3b248aef84cc474af838d7cc461b7f8fb7f5444ac75f4d8fc02e377R63).
=> Add manual trigger to PyPI publishing

benchmarks/scripts/expval_benchmark.py
Fixes #303.
This PR adds a function for generating the observable for a QCNN benchmarking circuit, based on [arXiv:1810.03787].(https://arxiv.org/abs/1810.03787) "Quantum Convolutional Neural Networks" by Iris Cong, Soonwon Choi, and Mikhail D. Lukin, where the observable of interest for an N-qubit QCNN circuit is $\sum_{i=2}^{N-1} Z_{i−1} X_i Z_{i+1}$ .
=> Add custom qcnn observable

benchmarks/scripts/common.py, docs/source/user_guide.rst
While working on a demo notebook, I came across the qiskit provided `num_nonlocal_gates()` as a preferred way to count the multi-qubit gates in a qiskit circuit. Quick update to use that internally.
[qiskit docs](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#num_nonlocal_gates) for this function
=> Use idiomatic circuit.num_nonlocal_gates for qiskit circuits

ucc/compile.py, ucc/tests/__init__.py, ucc/tests/mock_backends.py, ucc/tests/test_compile.py
The fix I went for was to allow users to pass 
1) a `return_gateset` in the form of `dict` keys (or a set) and use the `qiskit.transpile(circuit, basis_gates={'my', 'gate', 'set'}, optimization=0)` functionality to convert to a new basis automatically OR
2) a `target_device` whose allowable operations will be checked if that is an attribute present in that device. 
Added tests to confirm that the user-defined gateset is respected when it is passed, and the same for the target device.
**Note:** there is currently no functionality to check that a user-defined gateset is a) universal or b) available on the target_device, but currently these will cause errors that are reasonably straightforward to interpret for the user ('this operation is not available on this target'), so I think we can …
=> 342 target gateset

.github/release.yml
Now that we have Dependabot running, I though it would be nice to separate the dependency updates from other updates as part of the auto-generated release notes. This just copies the [setup in the Github docs](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes) for separating those by default.
=> Separate dependency updates in auto-generated release notes

CHANGELOG.md, pyproject.toml
(please ignore the incorrect branch name :P)
The CHANGELOG.rst was mixing markdown and rst, so I switched to markdown. This also works better with the auto-generated release notes.
=> Update version and changelog for 0.4.6 release

ucc/compile.py
Update the ucc.compile() docstring to reflect the default behavior when no target gate set is passed: 
> Defaults to the gateset of the target device, or if none is provided, the basis gates of the input circuit are not changed.
User guide already updated in https://github.com/unitaryfoundation/ucc/commit/d259f1749541920e7c72a833abcc76d587872404 - thanks Jordan!
=> Reword `ucc.compile()` docstring's `target_gateset` arg

docs/source/user_guide.rst, ucc/compile.py, ucc/tests/test_compile.py, ucc/transpilers/ucc_defaults.py
The current operation is 
1. Identify the target gateset:
a) `target_device.operation_names` if a target_device is provided, or
b) the target_gateset if that is provided, or
c) else {cx, rz, rx, ry, h} if neither is provided.
2. Translate the initial circuit into the provided gateset first, pre-optimization (This may not be necessary, as commenting it out doesn't break any tests, so UnitarySynthesis may be taking care of this).
3. Pass the target gateset to the UnitarySynthesis pass to optimize for that target basis. 
1c) is different than the previous behavior of leaving circuits alone if no target was specified. This way we aren't losing out on the optimization potential of the UnitarySynthesis pass.
=> Simplified and optimized logic for target gateset selection. 

pyproject.toml
This PR fixes a license metadata mismatch. See #499 
- pyproject.toml previously declared GPL-3.0
- Repo LICENSE and README.md state AGPLv3
Change:
- Set `[project].license = "AGPL-3.0-only"` in pyproject.toml to align with LICENSE and README.md.
Follow-ups (optional):
- Verify sdist/wheel license metadata shows AGPL.
- Optionally add a Trove classifier for AGPL: "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)".
=> chore(license): set AGPL-3.0-only in pyproject.toml to match LICENSE and README

.coveragerc
Related to #479 and as noticed by @ACE07-Sev, this change should ignore unit test code itself when calculating code coverage.
=> Ignore test code in test coverage
